version: "3.8"
services:
  app:
    build: .
    environment:
      TABLE_NAME: example
      DYNAMODB_ENDPOINT: http://dynamodb:8000/
      AWS_DEFAULT_REGION: eu-west-1
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: 1
      AWS_SECRET_ACCESS_KEY: 1
    working_dir: $PWD
    command: wait-for-it --strict --timeout=30 dynamodb:8000 -- ./_start-api.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:$PWD
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
